
-- to run this file: mysql -u <user> -p <your database name> < create_schema.sql

-- USE <your database name>
USE cs157a_library_system;

DROP TABLE IF EXISTS PaymentRecords;
DROP TABLE IF EXISTS BorrowRecords;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS ISBNs;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users
(
  UserID INT unsigned AUTO_INCREMENT,
  FullName VARCHAR(150) NOT NULL,
  Password VARCHAR(30) NOT NULL,
  Status VARCHAR(30) NOT NULL,
  Email VARCHAR(150) NOT NULL,
  Phone VARCHAR(20),
  Address VARCHAR(150),
  RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (UserID)
);

CREATE TABLE ISBNs(
  ISBN VARCHAR(13),
  Title VARCHAR(150),
  Author VARCHAR(150),
  Genre VARCHAR(30),
  PRIMARY KEY (ISBN)
);

CREATE TABLE Books
(
  BookID INT unsigned AUTO_INCREMENT,
  ISBN VARCHAR(13),
  CONSTRAINT isbn FOREIGN KEY (ISBN) REFERENCES ISBNs(ISBN) ON UPDATE CASCADE,
  Status VARCHAR(100) NOT NULL,
  PRIMARY KEY (BookID)
);

CREATE TABLE BorrowRecords
(
  RecordID BIGINT unsigned AUTO_INCREMENT,
  BookID INT unsigned,
  CONSTRAINT bookid FOREIGN KEY (BookID) REFERENCES Books(BookID) ON UPDATE CASCADE ON DELETE SET NULL,
  UserID INT unsigned,
  CONSTRAINT userid FOREIGN KEY (UserID) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE SET NULL,
  BorrowDate DATETIME,
  ReturnDate DATETIME,
  FineAmount DECIMAL(5,2),
  PRIMARY KEY (RecordID)
);

CREATE TABLE PaymentRecords
(
  PaymentID BIGINT unsigned AUTO_INCREMENT,
  UserID INT unsigned,
  CONSTRAINT useridpr FOREIGN KEY (UserID) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE SET NULL,
  PaymentAmount DECIMAL(6,2),
  PaymentDate DATETIME,
  PRIMARY KEY (PaymentID)
);

